<?php
/**
 * @file
 * This module displays a recent Tweet in a block, given a username.
 */

/**
 * Implements hook_block_info().
 */
function wes_twitter_block_info() {
  $blocks['twitter'] = array(
    'info' => t('Wes Twitter'),
    'cache' => DRUPAL_CACHE_PER_PAGE,
    'status' => TRUE,
    'region' => 'sidebar_second',
    'visibility' => 1,
  );
  $blocks['twitter_feed'] = array(
    'info' => t('Wes Twitter - Feed'),
    'cache' => DRUPAL_CACHE_PER_PAGE,
    'status' => FALSE,
    'region' => 'sidebar_second',
    'visibility' => 1,
  );
  return $blocks;
}

/**
 * Implements hook_block_configure().
 */
function wes_twitter_block_configure($delta = '') {
  $form = array();
  if ($delta == 'twitter') {
    $form['twitter'] = array(
      '#type' => 'fieldset',
      '#title' => t('Twitter.com settings'),
    );
    $form['twitter']['wes_twitter_username'] = array(
      '#type' => 'textfield',
      '#title' => 'Twitter Username',
      '#size' => 20,
      '#description' => t('Used to query search.twitter.com. Do not include @.'),
      '#default_value' => variable_get('wes_twitter_username', ''),
    );
  } elseif ($delta == 'twitter_feed') {
    $fom['twitter'] = array(
      '#type' => 'fieldset',
      '#title' => t('Twitter.com settings'),
    );
    $form['twitter']['wes_twitter_username'] = array(
      '#type' => 'textfield',
      '#title' => 'Twitter Username',
      '#size' => 20,
      '#description' => t('Used to query search.twitter.com. Do not include @.'),
      '#default_value' => variable_get('wes_twitter_username', ''),
    );
    $options = db_query("SELECT type, name FROM {node_type} WHERE disabled = 0")->fetchAllKeyed();
    $form['twitter']['wes_twitter_nodetype'] = array(
      '#type' => 'select',
      '#title' => t('Node type'),
      '#default_value' => variable_get('wes_twitter_nodetype', ''),
      '#options' => $options,
      '#description' => t('Select the node to pull content from.'),
    );
  }
  return $form;
}

/**
 * Implements hook_block_save().
 */
function wes_twitter_block_save($delta = '', $edit = array()) {
  if ($delta == 'twitter') {
    variable_set('wes_twitter_username', $edit['wes_twitter_username']);
  } elseif ($delta == 'twitter_feed') {
    variable_set('wes_twitter_username', $edit['wes_twitter_username']);
    variable_set('wes_twitter_nodetype', $edit['wes_twitter_nodetype']);
  }
}

/**
 * Implements hook_block_view().
 */
function wes_twitter_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'twitter':
      // partly lifted from ninesixtyrobots/template.php    
      $twitter_username = variable_get('wes_twitter_username', '');
      if ($twitter_username) {
        // query search.twitter.com; return tweets from the given user
        $response = drupal_http_request('http://search.twitter.com/search.json?q=from:' . $twitter_username);
        $data = json_decode($response->data);
        if (!empty($data->results)) {
          // take first tweet
          $tweet = $data->results[0]->text;
          $block['subject'] = l('@' . $twitter_username, 'http://twitter.com/' . $twitter_username);
          $block['content'] = _wes_twitter_block_contents($tweet);
        }
      }
      break;
    case 'twitter_feed':
      $node_type = variable_get('wes_twitter_nodetype', '');
      $result = db_query('SELECT nid FROM {node} WHERE type = :type AND status = 1 LIMIT 1', array(':type' => $node_type))->fetchObject();
      $nid = $result->nid;
      if ($nid) {
        $node = node_load($nid);
        $twitter_username = variable_get('wes_twitter_username', '');
        $block['subject'] = l('@' . $twitter_username, 'http://twitter.com/' . $twitter_username);
        $block['content'] = _wes_twitter_block_contents($node->title);
      }
      
      break;
  }
  return $block;
}

/**
 * Custom block content function.
 *
 * @see wes_twitter_block_view()
 */
function _wes_twitter_block_contents($tweet) {
  return array(
    '#markup' => $tweet,
  );
}